# Generated by Django 4.1.7 on 2023-10-04 14:59

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_image_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(null=True, upload_to=posts.models.post_image_location),
        ),
    ]
