# Generated by Django 4.1.7 on 2023-08-17 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_straight", models.BooleanField(default=True)),
                ("username", models.CharField(max_length=25, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "profile_picture",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "account_linkage_code",
                    models.CharField(blank=True, max_length=5, null=True, unique=True),
                ),
                (
                    "number_of_favourite_couples",
                    models.PositiveBigIntegerField(default=0),
                ),
                ("number_of_liked_posts", models.PositiveBigIntegerField(default=0)),
                (
                    "my_partner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
