# Generated by Django 4.1.7 on 2023-10-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='number_of_favourite_couples',
            new_name='number_of_admired_couples',
        ),
    ]
