# Generated by Django 4.1.7 on 2023-10-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('couples', '0001_initial'),
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admirer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('admirer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('couple', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='couples.couple')),
            ],
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
    ]
