# Generated by Django 4.1.7 on 2023-08-17 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Couple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "couple_data",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                ("started_dating", models.DateField(default=django.utils.timezone.now)),
                ("anniversaries", models.PositiveBigIntegerField(default=0)),
                ("fans", models.PositiveBigIntegerField(blank=True, default=0)),
                (
                    "last_anniversary",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "next_anniversary",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "relationship_status",
                    models.CharField(default="Dating", max_length=100),
                ),
                ("is_straight_couple", models.BooleanField(default=True)),
                ("limbo", models.BooleanField(default=False)),
                ("limbo_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("has_posts", models.BooleanField(default=False)),
                (
                    "partner_one",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_one",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "partner_two",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_two",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
    ]
