# Generated by Django 4.1.7 on 2023-10-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couple',
            old_name='fans',
            new_name='admirers',
        ),
    ]
